feat: rewrite in go
stegmanh/snake pull request #2
Opened 2018-07-11 03:32 UTC by jaredallard

Fixes #1

2018-07-13 17:26 UTC, j-crowe commented
I approve these changes to Snak.

2018-07-13 17:27 UTC, j-crowe requested changes
Please reference Buca Di Beppo in the bee movie script. Thx

2018-11-15 19:46 UTC, jaredallard commented
@stegmanh any idea when this will be merged? we need this in ASAP

2018-11-15 19:50 UTC, j-crowe commented
Approved

2018-11-17 16:06 UTC, stegmanh commented on main.go
> +Rotate around it.
Rotate what? This should be clearer to the audience

2018-11-17 16:09 UTC, stegmanh commented
Please update the commit with review feedback and we can discuss further

2018-11-18 00:38 UTC, jaredallard commented
@stegmanh fixed as per your feedback, please let's get this merged

2018-11-30 22:04 UTC, stegmanh commented
@jaredallard Im concerned with your chose of `Go` because of it's lack of immutable variables and pure functions. 

How about we get this in Haskell and I think I can seriously consider merging it within the fortnite. Thank you

2019-01-21 06:11 UTC, jaredallard commented
@stegmanh will get on it ASAP

2019-01-21 06:27 UTC, jaredallard commented
@stegmanh this has been done, please get this merged ASAP. need to use immediately

2019-01-22 01:59 UTC, stegmanh commented
It looks like you merely updated the PR name without a commit. I have to say. I respect the sheer audacity

2019-01-22 02:32 UTC, jaredallard commented
@stegmanh Apologies, I appear to have forgotten to push my code... Will fix immediately.

2019-01-22 06:13 UTC, jaredallard commented
@stegmanh updated, please merge asap!

2019-01-22 16:25 UTC, stegmanh commented
@jaredallard This looks really nice. Im not seeing any tests though?

2019-01-22 18:14 UTC, jaredallard commented
@stegmanh Of course, will get that added

2019-02-28 18:00 UTC, jaredallard commented
@stegmanh After many difficult nights, contemplating this very important feature... I've decided, along with many other developers opinions (@j-crowe among others), that good code written by good developers does not require tests. This can be seen at the greatest of companies, who's very semblance in life is to create solutions to the world's problems.

2019-04-12 03:53 UTC, jaredallard commented
@stegmanh please get this merged as soon as possible. I am facing a lot of external pressure to get this in.

2022-09-05 22:40 UTC, jaredallard commented
@stegmanh if we don't get this merged by tomorrow I will literally catch on fire. You have no idea the pressure I'm under to get this in

2022-11-06 17:44 UTC, stegmanh commented
Hey @jaredallard - I apologize for getting back to you so late, it's been beesy around these parts. 

It looks like instead of a haskell implementation you accidentally committed the entire script of the Bee movie? If this unblocks you I'd still be happy to merge..

2022-12-11 07:16 UTC, closed without merging